#!/usr/bin/env bash

eval $(./scripts/colors | sed 's/\(.*\)=\(.*\)/export \1="\2"/g')

clear

echo
./scripts/banner
echo
                     
echo -e "${GREEN}Xahau(d) - JS Hooks ALPHA TOOLKIT${END}"
echo -e "                     ^^ EARLY STAGE! Expect dragons! 🐉 🐉"
echo
echo -e "${BLUE}Installs & runs:${END}"
echo "    - Local JS Hooks enabled Xahau instance"
echo "        - Network ID 65535 to disable TX signature verification"
echo "    - Technical Explorer"
echo "    - Log Watcher (rippled in trace, filtering on Hook info)"
echo "    - JS Hooks compiler (JS to Hook) & deployment"
echo "    - Transaction Generation Helper script"

echo
echo -e "${BLUE}Checking dependencies:${END}"

./scripts/install-check-prerequisites ; [[ $? -gt 0 ]] && echo -e "${RED}Dependency ERROR${END}" && exit 1 || echo -e "${GREEN}Dependencies OK${END}"

echo
echo -e "${BLUE}Building/running Docker Image:${END}"

echo
echo -e "${PURPLE}XAHAUD${END}"
./scripts/xahaud

echo
echo -e "${PURPLE}JS HOOK BUILDER${END}"
./scripts/hook-builder

echo
echo -e "${PURPLE}TECHNICAL EXPLORER${END}"
./scripts/technical-explorer


##### Done

echo